/*
 * Segment Public API
 *
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 
 *
 * The version of the OpenAPI document: 73.4.1
 * Contact: friends@segment.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Segment.PublicApi.Client.OpenAPIDateConverter;

namespace Segment.PublicApi.Model
{
    /// <summary>
    /// Defines a CSV export of an audience.
    /// </summary>
    [DataContract(Name = "AudienceCsvExport")]
    public partial class AudienceCsvExport : IEquatable<AudienceCsvExport>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudienceCsvExport" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AudienceCsvExport() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AudienceCsvExport" /> class.
        /// </summary>
        /// <param name="exportId">The id of the export. (required).</param>
        /// <param name="status">The status of the export. It currently can be IN_PROGRESS, SUCCESS, FAIL. (required).</param>
        /// <param name="startedAt">When the export started. (required).</param>
        /// <param name="finishedAt">When the export finished..</param>
        /// <param name="urls">Presigned S3 URLs for the exported CSV parts. Present only when status is SUCCESS. URLs are signed when the export completes, are typically valid for approximately one day, and are not refreshed by polling..</param>
        /// <param name="expiresAt">When the export expires and can no longer be retrieved, when known..</param>
        /// <param name="error">Error message if applicable..</param>
        public AudienceCsvExport(string exportId = default(string), string status = default(string), string startedAt = default(string), string finishedAt = default(string), List<string> urls = default(List<string>), string expiresAt = default(string), string error = default(string))
        {
            // to ensure "exportId" is required (not null)
            if (exportId == null)
            {
                throw new ArgumentNullException("exportId is a required property for AudienceCsvExport and cannot be null");
            }
            this.ExportId = exportId;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for AudienceCsvExport and cannot be null");
            }
            this.Status = status;
            // to ensure "startedAt" is required (not null)
            if (startedAt == null)
            {
                throw new ArgumentNullException("startedAt is a required property for AudienceCsvExport and cannot be null");
            }
            this.StartedAt = startedAt;
            this.FinishedAt = finishedAt;
            this.Urls = urls;
            this.ExpiresAt = expiresAt;
            this.Error = error;
        }

        /// <summary>
        /// The id of the export.
        /// </summary>
        /// <value>The id of the export.</value>
        [DataMember(Name = "exportId", IsRequired = true, EmitDefaultValue = true)]
        public string ExportId { get; set; }

        /// <summary>
        /// The status of the export. It currently can be IN_PROGRESS, SUCCESS, FAIL.
        /// </summary>
        /// <value>The status of the export. It currently can be IN_PROGRESS, SUCCESS, FAIL.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// When the export started.
        /// </summary>
        /// <value>When the export started.</value>
        [DataMember(Name = "startedAt", IsRequired = true, EmitDefaultValue = true)]
        public string StartedAt { get; set; }

        /// <summary>
        /// When the export finished.
        /// </summary>
        /// <value>When the export finished.</value>
        [DataMember(Name = "finishedAt", EmitDefaultValue = false)]
        public string FinishedAt { get; set; }

        /// <summary>
        /// Presigned S3 URLs for the exported CSV parts. Present only when status is SUCCESS. URLs are signed when the export completes, are typically valid for approximately one day, and are not refreshed by polling.
        /// </summary>
        /// <value>Presigned S3 URLs for the exported CSV parts. Present only when status is SUCCESS. URLs are signed when the export completes, are typically valid for approximately one day, and are not refreshed by polling.</value>
        [DataMember(Name = "urls", EmitDefaultValue = false)]
        public List<string> Urls { get; set; }

        /// <summary>
        /// When the export expires and can no longer be retrieved, when known.
        /// </summary>
        /// <value>When the export expires and can no longer be retrieved, when known.</value>
        [DataMember(Name = "expiresAt", EmitDefaultValue = false)]
        public string ExpiresAt { get; set; }

        /// <summary>
        /// Error message if applicable.
        /// </summary>
        /// <value>Error message if applicable.</value>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudienceCsvExport {\n");
            sb.Append("  ExportId: ").Append(ExportId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  FinishedAt: ").Append(FinishedAt).Append("\n");
            sb.Append("  Urls: ").Append(Urls).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AudienceCsvExport);
        }

        /// <summary>
        /// Returns true if AudienceCsvExport instances are equal
        /// </summary>
        /// <param name="input">Instance of AudienceCsvExport to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AudienceCsvExport input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ExportId == input.ExportId ||
                    (this.ExportId != null &&
                    this.ExportId.Equals(input.ExportId))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.StartedAt == input.StartedAt ||
                    (this.StartedAt != null &&
                    this.StartedAt.Equals(input.StartedAt))
                ) && 
                (
                    this.FinishedAt == input.FinishedAt ||
                    (this.FinishedAt != null &&
                    this.FinishedAt.Equals(input.FinishedAt))
                ) && 
                (
                    this.Urls == input.Urls ||
                    this.Urls != null &&
                    input.Urls != null &&
                    this.Urls.SequenceEqual(input.Urls)
                ) && 
                (
                    this.ExpiresAt == input.ExpiresAt ||
                    (this.ExpiresAt != null &&
                    this.ExpiresAt.Equals(input.ExpiresAt))
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExportId != null)
                {
                    hashCode = (hashCode * 59) + this.ExportId.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.StartedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartedAt.GetHashCode();
                }
                if (this.FinishedAt != null)
                {
                    hashCode = (hashCode * 59) + this.FinishedAt.GetHashCode();
                }
                if (this.Urls != null)
                {
                    hashCode = (hashCode * 59) + this.Urls.GetHashCode();
                }
                if (this.ExpiresAt != null)
                {
                    hashCode = (hashCode * 59) + this.ExpiresAt.GetHashCode();
                }
                if (this.Error != null)
                {
                    hashCode = (hashCode * 59) + this.Error.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
