/*
 * Segment Public API
 *
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 
 *
 * The version of the OpenAPI document: 69.0.0
 * Contact: friends@segment.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Segment.PublicApi.Client.OpenAPIDateConverter;

namespace Segment.PublicApi.Model
{
    /// <summary>
    /// Defines the parameters needed to cancel a sync for a RETL connection.
    /// </summary>
    [DataContract(Name = "CancelReverseETLSyncForModelInput")]
    public partial class CancelReverseETLSyncForModelInput : IEquatable<CancelReverseETLSyncForModelInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelReverseETLSyncForModelInput" /> class.
        /// </summary>
        /// <param name="reasonForCanceling">The reason for canceling the sync. - IncorrectModel &#x3D; 0 - IncorrectDest &#x3D; 1 - IncorrectKeys &#x3D; 2 - IncorrectMapping &#x3D; 3 - Other &#x3D; 4.</param>
        public CancelReverseETLSyncForModelInput(decimal reasonForCanceling = default(decimal))
        {
            this.ReasonForCanceling = reasonForCanceling;
        }

        /// <summary>
        /// The reason for canceling the sync. - IncorrectModel &#x3D; 0 - IncorrectDest &#x3D; 1 - IncorrectKeys &#x3D; 2 - IncorrectMapping &#x3D; 3 - Other &#x3D; 4
        /// </summary>
        /// <value>The reason for canceling the sync. - IncorrectModel &#x3D; 0 - IncorrectDest &#x3D; 1 - IncorrectKeys &#x3D; 2 - IncorrectMapping &#x3D; 3 - Other &#x3D; 4</value>
        [DataMember(Name = "reasonForCanceling", EmitDefaultValue = false)]
        public decimal ReasonForCanceling { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CancelReverseETLSyncForModelInput {\n");
            sb.Append("  ReasonForCanceling: ").Append(ReasonForCanceling).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CancelReverseETLSyncForModelInput);
        }

        /// <summary>
        /// Returns true if CancelReverseETLSyncForModelInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CancelReverseETLSyncForModelInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancelReverseETLSyncForModelInput input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ReasonForCanceling == input.ReasonForCanceling ||
                    this.ReasonForCanceling.Equals(input.ReasonForCanceling)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ReasonForCanceling.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
