/*
 * Segment Public API
 *
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 
 *
 * The version of the OpenAPI document: 73.4.0
 * Contact: friends@segment.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Segment.PublicApi.Client.OpenAPIDateConverter;

namespace Segment.PublicApi.Model
{
    /// <summary>
    /// Verifies a Warehouse connection using a Credential by attempting to connect to it.
    /// </summary>
    [DataContract(Name = "CreateValidationInWarehouseV2Input")]
    public partial class CreateValidationInWarehouseV2Input : IEquatable<CreateValidationInWarehouseV2Input>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateValidationInWarehouseV2Input" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateValidationInWarehouseV2Input() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateValidationInWarehouseV2Input" /> class.
        /// </summary>
        /// <param name="credentialId">The id of the Credential to validate the connection with. The Warehouse type is derived from this Credential. (required).</param>
        /// <param name="settings">A key-value object that contains the settings for a Warehouse, derived from its associated Credential..</param>
        public CreateValidationInWarehouseV2Input(string credentialId = default(string), Dictionary<string, Object> settings = default(Dictionary<string, Object>))
        {
            // to ensure "credentialId" is required (not null)
            if (credentialId == null)
            {
                throw new ArgumentNullException("credentialId is a required property for CreateValidationInWarehouseV2Input and cannot be null");
            }
            this.CredentialId = credentialId;
            this.Settings = settings;
        }

        /// <summary>
        /// The id of the Credential to validate the connection with. The Warehouse type is derived from this Credential.
        /// </summary>
        /// <value>The id of the Credential to validate the connection with. The Warehouse type is derived from this Credential.</value>
        [DataMember(Name = "credentialId", IsRequired = true, EmitDefaultValue = true)]
        public string CredentialId { get; set; }

        /// <summary>
        /// A key-value object that contains the settings for a Warehouse, derived from its associated Credential.
        /// </summary>
        /// <value>A key-value object that contains the settings for a Warehouse, derived from its associated Credential.</value>
        [DataMember(Name = "settings", EmitDefaultValue = false)]
        public Dictionary<string, Object> Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateValidationInWarehouseV2Input {\n");
            sb.Append("  CredentialId: ").Append(CredentialId).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateValidationInWarehouseV2Input);
        }

        /// <summary>
        /// Returns true if CreateValidationInWarehouseV2Input instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateValidationInWarehouseV2Input to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateValidationInWarehouseV2Input input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CredentialId == input.CredentialId ||
                    (this.CredentialId != null &&
                    this.CredentialId.Equals(input.CredentialId))
                ) && 
                (
                    this.Settings == input.Settings ||
                    this.Settings != null &&
                    input.Settings != null &&
                    this.Settings.SequenceEqual(input.Settings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CredentialId != null)
                {
                    hashCode = (hashCode * 59) + this.CredentialId.GetHashCode();
                }
                if (this.Settings != null)
                {
                    hashCode = (hashCode * 59) + this.Settings.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
