/*
 * Segment Public API
 *
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 
 *
 * The version of the OpenAPI document: 73.0.6
 * Contact: friends@segment.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Segment.PublicApi.Client.OpenAPIDateConverter;

namespace Segment.PublicApi.Model
{
    /// <summary>
    /// EventPropertyAlpha
    /// </summary>
    [DataContract(Name = "EventPropertyAlpha")]
    public partial class EventPropertyAlpha : IEquatable<EventPropertyAlpha>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public EventPropertyType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventPropertyAlpha" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventPropertyAlpha() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventPropertyAlpha" /> class.
        /// </summary>
        /// <param name="name">Property name. (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="eventName">The event this property belongs to. (required).</param>
        /// <param name="lastSeenAt">ISO timestamp of when the property was last seen. (required).</param>
        /// <param name="samples">Sample values for this property. Only present when includeSampleValues is true..</param>
        public EventPropertyAlpha(string name = default(string), EventPropertyType type = default(EventPropertyType), string eventName = default(string), string lastSeenAt = default(string), List<string> samples = default(List<string>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for EventPropertyAlpha and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            // to ensure "eventName" is required (not null)
            if (eventName == null)
            {
                throw new ArgumentNullException("eventName is a required property for EventPropertyAlpha and cannot be null");
            }
            this.EventName = eventName;
            // to ensure "lastSeenAt" is required (not null)
            if (lastSeenAt == null)
            {
                throw new ArgumentNullException("lastSeenAt is a required property for EventPropertyAlpha and cannot be null");
            }
            this.LastSeenAt = lastSeenAt;
            this.Samples = samples;
        }

        /// <summary>
        /// Property name.
        /// </summary>
        /// <value>Property name.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The event this property belongs to.
        /// </summary>
        /// <value>The event this property belongs to.</value>
        [DataMember(Name = "eventName", IsRequired = true, EmitDefaultValue = true)]
        public string EventName { get; set; }

        /// <summary>
        /// ISO timestamp of when the property was last seen.
        /// </summary>
        /// <value>ISO timestamp of when the property was last seen.</value>
        [DataMember(Name = "lastSeenAt", IsRequired = true, EmitDefaultValue = true)]
        public string LastSeenAt { get; set; }

        /// <summary>
        /// Sample values for this property. Only present when includeSampleValues is true.
        /// </summary>
        /// <value>Sample values for this property. Only present when includeSampleValues is true.</value>
        [DataMember(Name = "samples", EmitDefaultValue = false)]
        public List<string> Samples { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventPropertyAlpha {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("  LastSeenAt: ").Append(LastSeenAt).Append("\n");
            sb.Append("  Samples: ").Append(Samples).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EventPropertyAlpha);
        }

        /// <summary>
        /// Returns true if EventPropertyAlpha instances are equal
        /// </summary>
        /// <param name="input">Instance of EventPropertyAlpha to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventPropertyAlpha input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.EventName == input.EventName ||
                    (this.EventName != null &&
                    this.EventName.Equals(input.EventName))
                ) && 
                (
                    this.LastSeenAt == input.LastSeenAt ||
                    (this.LastSeenAt != null &&
                    this.LastSeenAt.Equals(input.LastSeenAt))
                ) && 
                (
                    this.Samples == input.Samples ||
                    this.Samples != null &&
                    input.Samples != null &&
                    this.Samples.SequenceEqual(input.Samples)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.EventName != null)
                {
                    hashCode = (hashCode * 59) + this.EventName.GetHashCode();
                }
                if (this.LastSeenAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastSeenAt.GetHashCode();
                }
                if (this.Samples != null)
                {
                    hashCode = (hashCode * 59) + this.Samples.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
