/*
 * Segment Public API
 *
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 
 *
 * The version of the OpenAPI document: 59.6.0
 * Contact: friends@segment.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Segment.PublicApi.Client.OpenAPIDateConverter;

namespace Segment.PublicApi.Model
{
    /// <summary>
    /// The Personalization Input Entity.
    /// </summary>
    [DataContract(Name = "PersonalizationInputEntity")]
    public partial class PersonalizationInputEntity : IEquatable<PersonalizationInputEntity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonalizationInputEntity" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PersonalizationInputEntity() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonalizationInputEntity" /> class.
        /// </summary>
        /// <param name="properties">properties (required).</param>
        /// <param name="relationshipSlug">The relationship slug for the entity. (required).</param>
        public PersonalizationInputEntity(List<string> properties = default(List<string>), string relationshipSlug = default(string))
        {
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for PersonalizationInputEntity and cannot be null");
            }
            this.Properties = properties;
            // to ensure "relationshipSlug" is required (not null)
            if (relationshipSlug == null)
            {
                throw new ArgumentNullException("relationshipSlug is a required property for PersonalizationInputEntity and cannot be null");
            }
            this.RelationshipSlug = relationshipSlug;
        }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Properties { get; set; }

        /// <summary>
        /// The relationship slug for the entity.
        /// </summary>
        /// <value>The relationship slug for the entity.</value>
        [DataMember(Name = "relationshipSlug", IsRequired = true, EmitDefaultValue = true)]
        public string RelationshipSlug { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PersonalizationInputEntity {\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  RelationshipSlug: ").Append(RelationshipSlug).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PersonalizationInputEntity);
        }

        /// <summary>
        /// Returns true if PersonalizationInputEntity instances are equal
        /// </summary>
        /// <param name="input">Instance of PersonalizationInputEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PersonalizationInputEntity input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Properties == input.Properties ||
                    this.Properties != null &&
                    input.Properties != null &&
                    this.Properties.SequenceEqual(input.Properties)
                ) && 
                (
                    this.RelationshipSlug == input.RelationshipSlug ||
                    (this.RelationshipSlug != null &&
                    this.RelationshipSlug.Equals(input.RelationshipSlug))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                if (this.RelationshipSlug != null)
                {
                    hashCode = (hashCode * 59) + this.RelationshipSlug.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
